apiVersion: v1
kind: Service
metadata:
  name: gitea-ssh
  namespace: gitea
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: gitea
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 2222
      nodePort: 30222
