apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: hello-world-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: fkcurrie/hello-world
      labels:
        - self-hosted
      dockerdWithinRunnerContainer: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
